# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: http://bytes.codes
title: Bytes.Codes
subtitle: Code and random ramblings.
author: Brendan McAdams
simple_search: https://www.google.com/search
description:
logo: logo_small.png


# Github repositories
github_user: bwmcadams
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: rit
twitter_tweet_button: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-theme-hacker

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
