# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: http://bytes.codes
title: Bytes.Codes
subtitle: Code and random ramblings.
author: Brendan McAdams
simple_search: https://www.google.com/search
description:
logo: logo_small.png
owner: "Brendan McAdams"
year: "2011 - 2020"

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: brendan@bytes.codes

# Github repositories
github_user: bwmcadams
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: rit
twitter_tweet_button: true

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:day/:title/
code_dir: code
category_dir: categories
#markdown: kramdown
#kramdown:
#  enable_coderay: true
#  syntax_highlighter_opts:
#    line_numbers: inline # nil, inline, list, table
#    css: style
#rdiscount:
#  extensions:
#    - autolink
#    - footnotes
#    - smart

paginate: 5 # Posts per page on the blog index
paginate_path: /page/:num/  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

source: .
destination: ./_site
permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

